all: install

install:
	cp ./rt61ap.ko ../../targets/fs.src/lib/
	cp ./RT2561.bin ../../targets/fs.src/lib/
	cp ./RT2561S.bin ../../targets/fs.src/lib/
	cp ./RT2661.bin ../../targets/fs.src/lib/
	cp ./RT61AP.dat ../../targets/fs.src/lib/
	cp ./rt61apd ../../targets/fs.src/lib/
